#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ $0 != "utils/import" ]]; then
	echo "ERROR: Must be run from repo root." >&2
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "Overwrite repo file with installed file."
	echo "Usage: $0 <file>..."
	echo "Example: $0 dotfiles/.bashrc"
	exit
fi

while [ $# -gt 0 ]; do

	file=$1; shift

	if [[ $file == /* ]]; then
		echo "ERROR: Must use relative file paths." >&2
		exit 1
	fi

	if [ -d "$file" ]; then
		continue
	fi

	dir=$(dirname $file)
	base=$(basename $file)

	target=
	if [[ $dir == "dotfiles" ]]; then
		target="$HOME/$base"
	elif [[ $dir == "bin" ]]; then
		target="/usr/local/bin/$base"
	elif [[ $dir == "sbin" ]]; then
		target="/usr/local/sbin/$base"
	fi

	echo "INFO: Importing file \"$target\"."
	cp -d "$target" "$file"

done
